name = "yeni-depo"
compatibility_date = "2026-09-24"
pages_build_output_dir = "."

[vars]
SUPABASE_URL = "https://ztkopywelwximjiopdci.supabase.co"
SUPABASE_PUBLISHABLE_KEY = "sb_publishable_mkA2Q3ivb3uhxSb9QxF6cg_MxcfZGJ-"
